saving_config:
  file_name: Video_
  extension: .mp4
  start_index: 27
  save_dir: "video_saved"



video_config:
  video_start: 0            
  video_end: 1351           
  video_size: 150           
  num_of_retry_attempts: 30 
  pool: 50
  
 # Video part start (Default = 0)
 # Video part end, +1 for looping (Default = 1150)
 # Around 2MB * Size
 # Number of attempts to reconnect
 # Pool is parallel downloading



timeout_config:            
  login_max_timeout: 200    
  video_max_timeout: 400    
  start_timeout: 5          
  step: 5  
  


login_config:
  login_url: https://www.openu.ac.il/
  usernameId: p_user
  passwordId: p_sisma
  IDId: p_mis_student
  submit_xpath: //*[@id="login_sso"]/fieldset/input[1]
  button_id: openu_myop_plugin_MyOpAppsBtn
  fid: openu_myop_plugin_person_iframeId
  


filter_config:
  key_a: method
  key_b: params
  key_c: initialPriority
  key_d: url
  filter_a: Network.requestWillBeSent
  filter_b: request
  filter_c: High
  filter_d: https://souvod.bynetcdn.com/vod
  
  split_text_a: "00000_"
  split_text_b: ".ts"